force-app/main/default/objects/CS_AzureSSO__c/CS_AzureSSO__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CS AzureSSO</label>
</CustomObject>

force-app/main/default/objects/CS_AzureSSO__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Azure app client id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>Scopes for the auth call</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scope</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/TenantId__c.field-meta.xml
<CustomField>
    <fullName>TenantId__c</fullName>
    <description>Azure app tenant Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tenant Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Thumbprint__c.field-meta.xml
<CustomField>
    <fullName>Thumbprint__c</fullName>
    <description>Certificate thumbprint for auth matching</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Thumbprint</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Token1__c.field-meta.xml
<CustomField>
    <fullName>Token1__c</fullName>
    <description>Access token first 255 characters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Access Token Part 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Token2__c.field-meta.xml
<CustomField>
    <fullName>Token2__c</fullName>
    <description>Access token second 255 characters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Access Token Part 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Token3__c.field-meta.xml
<CustomField>
    <fullName>Token3__c</fullName>
    <description>Access token third 255 characters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Access Token Part 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Token4__c.field-meta.xml
<CustomField>
    <fullName>Token4__c</fullName>
    <description>Access token fourth 255 characters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Access Token Part 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CS_AzureSSO__c/fields/Token5__c.field-meta.xml
<CustomField>
    <fullName>Token5__c</fullName>
    <description>Access token fifth 255 characters</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Access Token Part 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JWTAzureController.cls
public with sharing class JWTAzureController {
    @AuraEnabled(Cacheable=false)
    public static String getAccessToken(){
        //get org custom setting for callout
        CS_AzureSSO__c CS = CS_AzureSSO__c.getOrgDefaults();

        //setup auth parameters
        JWTAzure jwt = new JWTAzure();
        jwt.cert = 'AzureSSO'; //put the name of your cert here
        jwt.iss = CS.ClientId__c;
        jwt.sub = CS.ClientId__c;
        jwt.aud = 'https://login.microsoftonline.com/' + CS.TenantId__c + '/oauth2/v2.0/token';
        jwt.x5t = CS.Thumbprint__c;

        // invoke the flow and obtain an access_token
        String access_token = JWTAzureFlow.getAccessToken(CS.ClientId__c, CS.TenantId__c, CS.Scope__c, jwt);
        CS.Token1__c = access_token.length() > 255 ? access_token.substring(0,255) : access_token;
        CS.Token2__c = access_token.length() > 510 ? access_token.substring(255,510) : access_token.substring(255,access_token.length());
        CS.Token3__c = access_token.length() > 765 ? access_token.substring(510,765) : access_token.substring(510,access_token.length());
        CS.Token4__c = access_token.length() > 1020 ? access_token.substring(765,1020) : access_token.substring(765,access_token.length());
        CS.Token5__c = access_token.length() > 1275 ? access_token.substring(1020,1275) : access_token.substring(1020,access_token.length());

        //update the custom setting
        try{
            update CS;
        }catch (DmlException e){
            System.debug('Error updating custom setting: ' + e.getMessage());
        }

        System.debug('Access Token: ' + access_token);
        System.debug('Access Token Length: ' + access_token.length()); //about 1250 characters
        return access_token;
    }
}